# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
# Log in to DockerHub
- script: |
    docker login -u abdulsamad001 -p Hafizhabib123
  displayName: 'abdulsamad001'

# Push Docker image to DockerHub
- script: |
    docker tag expressapi:latest abdulsamad001/expressapi
    docker push abdulsamad001/expressapi:latest
  displayName: 'abdulsamad001'

# Update Kubernetes deployment to use the new image
- script: |
    kubectl set image deployment/expressapi-deployment expressapi=abdulsamad001/expressapi:latest
  displayName: 'abdulsamad001'