# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t abdulsamad001/expressapi:latest .
      env:
        DOCKER_CLI_ACI_USERNAME: ${{ secrets.abdulsamad001 }}
        DOCKER_CLI_ACI_PASSWORD: ${{ secrets.Hafizhabib123}}

    - name: Log in to DockerHub
      run: |
        echo $DOCKER_CLI_ACI_PASSWORD | docker login -u $DOCKER_CLI_ACI_abdulsamad001 --Hafizhabib123-stdin

    - name: Push Docker image to DockerHub
      run: docker push abdulsamad001/expressapi:latest


  

  

