# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    displayName: 'Install Node.js'
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t abdulsamad001/expressapi:latest .
      
    - name: Log in to DockerHub
      run: docker login -u abdulsamad001 -p Hafizhabib123

    - name: Push Docker image to DockerHub
      run: docker push abdulsamad001/expressapi:latest

      name: Deploy to Kubernetes
        run: |
          kubectl apply -f azure-manifest.yaml
        

- script: |
    npm install
  displayName: 'npm install'

  
      
